// <auto-generated />
using System;
using GinasioIsla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GinasioIsla.Migrations
{
    [DbContext(typeof(GinasioContext))]
    partial class GinasioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GinasioIsla.Models.Aluno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Apelido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("GinasioIsla.Models.Inscricao", b =>
                {
                    b.Property<int>("InscricaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscricaoID"), 1L, 1);

                    b.Property<int>("AlunoID")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadeID")
                        .HasColumnType("int");

                    b.HasKey("InscricaoID");

                    b.HasIndex("AlunoID");

                    b.HasIndex("ModalidadeID");

                    b.ToTable("Inscricao");
                });

            modelBuilder.Entity("GinasioIsla.Models.Modalidade", b =>
                {
                    b.Property<int>("ModalidadeID")
                        .HasColumnType("int");

                    b.Property<int>("HorasSemanais")
                        .HasColumnType("int");

                    b.Property<string>("NomeModalidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModalidadeID");

                    b.ToTable("Modalidade");
                });

            modelBuilder.Entity("GinasioIsla.Models.Inscricao", b =>
                {
                    b.HasOne("GinasioIsla.Models.Aluno", "Aluno")
                        .WithMany("Inscricoes")
                        .HasForeignKey("AlunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GinasioIsla.Models.Modalidade", "Modalidade")
                        .WithMany("Inscricoes")
                        .HasForeignKey("ModalidadeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Modalidade");
                });

            modelBuilder.Entity("GinasioIsla.Models.Aluno", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("GinasioIsla.Models.Modalidade", b =>
                {
                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
